#!/bin/sh

PORT_SQL=$1
SET_FILE=$2
OUTPUT_PATH=$3

# Executable file location. Change 'path' to the colibri2 top installation directory.
EXECUTABLE=/app/colibri2/cli/export3cli.py

# PostgreSQL database url. Default for a PostgreSQL server is postgres:postgres@localhost:5432/postgres
DB_URL=postgresql+psycopg2://colibri2:Stulajter@localhost:$PORT_SQL/colibri2

# Table names
FLASK_TABLE=superformulas
INVALID_TABLE=invalid_superformulas
TRANS_TABLE=transformations
RULE_TABLE=rules

if [ -z "$3" ]; then
  echo "Usage: export3 <output path>"
  exit 1
fi

export COLIB2_LOGGING__LEVEL=CRITICAL

COMMAND=`echo python3 $EXECUTABLE -o "$OUTPUT_PATH" -d "$DB_URL"  -f "$FLASK_TABLE" -t "$TRANS_TABLE" \
    -R "$RULE_TABLE" -Z "$SET_FILE"`

echo $COMMAND
sh -c "$COMMAND"
